//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Tasks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksTable
    {
        public int Task_ID { get; set; }
        public string Description { get; set; }
        public string Completion_Status { get; set; }
    }
}
